name = "godemove"
compatibility_date = "2026-04-15"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
id = "dad0fd95cd8348439c282a0d8db88847"
preview_id = "a680a379979d4c678e249d56636039a0"

[[d1_databases]]
binding = "DB"
database_name = "cmsdb"
database_id = "fd58869e-453a-4de2-a2c5-f869189ad03b"
